name: Bun Scraper

on:
  schedule:
    - cron: '0 20 * * *' # Runs at 13:00 UTC every day
  workflow_dispatch:  

jobs:
  python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt 

    - name: Run Python script
      run: |
        python scraper_noticias/scraper_bun/scrape_links.py

    - name: Check JSON file
      run: |
        if [ -f "scraper_noticias/scraper_bun/bun_jsons/news_links.json" ]; then
          echo "File exists: scraper_noticias/scraper_bun/bun_jsons/news_links.json"
        else
          echo "File does not exist: scraper_noticias/scraper_bun/bun_jsons/news_links.json"
          exit 1  # Exit with an error code if the file is missing
        fi
      working-directory: ${{ github.workspace }}
        
    - name: Save JSON as artifact
      uses: actions/upload-artifact@v3
      with:
        name: generated-json
        path: scraper_noticias/scraper_bun/bun_jsons/news_links.json

  bun:
    needs: python
    runs-on: ubuntu-latest

    steps:
    - name: Set up Bun
      uses: oven-sh/setup-bun@v1

    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        cd scraper_noticias/scraper_bun
        bun install

    - name: Download JSON artifact
      uses: actions/download-artifact@v3
      with:
        name: generated-json
        path: scraper_noticias/scraper_bun/bun_jsons
      
    - name: Check JSON Content
      run: |
        cat scraper_noticias/scraper_bun/bun_jsons/news_links.json

    - name: List downloaded files
      run: ls -R scraper_noticias/scraper_bun/bun_jsons/


    - name: Run bun scraper
      working-directory: scraper_noticias/scraper_bun
      run: |
        bun index.js

    - name: Commit and push changes
      run: |
            git config --global user.name "opencore"
            git config --global user.email "opencore@unap.cl
            git add scraper_noticias/scraper_bun/bun_jsons/articles.json
            git commit -m "upload articles.json from bun"
            git push


