name: Scrap and load

on:
  schedule:
    - cron: '0 14 * * *' # Runs at 14:00 UTC every day
    #cron to run at 11:00 UTC every day
    - cron: '0 11 * * *' # Runs at 11:00 UTC every day
    #cron to run at 00:00 UTC every day
    - cron: '0 0 * * *' # Runs at 00:00 UTC every day
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DEBUG: ${{ secrets.DEBUG }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      MONGO_URI: ${{ secrets.MONGO_URI }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.8

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Run scraper
        run: python main.py

      - name: Do analysis
        run: |
          cd openCore
          python analisisSentimiento.py

      - name: Dump data
        run: |
          cd openCore
          python manage.py loadnews

      - name: Commit and push changes
        run: |
          git config --global user.email "opencore@unap.cl"
          git config --global user.name "opencore"
          git add openCore/newsdb_historical.json
          git commit -m "loaded news to repo"
          git push
